package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"cmp"
	"context"
	"encoding/json"
	"log"
	"net/http"
	"slices"
	"sync"

	"github.com/xuqingfeng/TopHackerNews/graph/model"
)

const HN_TOPSTORIES_API = "https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty"

// TopStories is the resolver for the topStories field.
func (r *queryResolver) TopStories(ctx context.Context, offset *int, limit *int) ([]*model.Story, error) {
	r.topStories = make([]*model.Story, 0)

	// get all top stories' ids
	resp, err := http.Get(HN_TOPSTORIES_API)
	log.Printf("fetching stories, offset:%d limit:%d", *offset, *limit)
	if err != nil {
		log.Printf("err: %v", err)
		return nil, err
	}
	if resp.StatusCode == http.StatusOK {
		ids := new([]int)
		err = json.NewDecoder(resp.Body).Decode(ids)
		// log.Printf("ids: %v", ids)
		if err != nil {
			return nil, err
		}

		var wg sync.WaitGroup
		for i, id := range *ids {
			if i < *offset {
				continue
			}
			if i >= *offset+*limit {
				break
			}
			// get every story's detail concurrently
			wg.Add(1)
			go fetchStoryDetail(id, r, &wg)
		}
		wg.Wait()
	}

	slices.SortFunc(r.topStories, func(a, b *model.Story) int {
		return cmp.Compare(b.Score, a.Score)
	})

	return r.topStories, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
