// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Story struct {
	By          string   `json:"by"`
	Descendants int      `json:"descendants"`
	ID          string   `json:"id"`
	Kids        []string `json:"kids,omitempty"`
	Score       int      `json:"score"`
	Time        int      `json:"time"`
	Title       string   `json:"title"`
	Type        string   `json:"type"`
	URL         string   `json:"url"`
}
